services:
  visualization:
    build:
      context: ./visualization
      dockerfile: Dockerfile
    container_name: review-galaxy-visualization
    ports:
      - "4200:4200"
    environment:
      - MIDDLEWARE_ADDR=http://localhost:9000/
    networks:
      review-galaxy-network:
        ipv4_address: 172.20.0.2

  middleware:
    build:
      context: ./middleware
      dockerfile: Dockerfile
    container_name: review-galaxy-middleware
    entrypoint: ["java", "-jar", "-Dserver.port=3000", "/app/app.jar"]
    ports:
      - "3000:3000"
    networks:
      review-galaxy-network:
        ipv4_address: 172.20.0.3

networks:
  review-galaxy-network:
    name: review-galaxy-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
