name: Docker Build and Deploy

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'main'
      
permissions:
  id-token: write
  contents: read
  
env:
  REGISTRY: ${{ secrets.REGISTRY_NAME }}.azurecr.io

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    if: github.event_name != 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Compose Build
        run: docker compose -f docker-compose.yaml build

      - name: List All Created Images
        run: docker image ls

      - name: Print Build SHA
        run: echo ${{ github.sha }}


  build-deploy:
    name: Build and Deploy Docker Images
    runs-on: ubuntu-latest
    environment: Prod
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Az Login
        uses: Azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Az acr Login
        run: az acr login --name ${{ secrets.REGISTRY_NAME }}
        
      - name: Docker Compose Build
        run: docker compose -f docker-compose.yaml build

      - name: List All Created Images
        run: docker image ls

      - name: Print Build SHA
        run: echo ${{ github.sha }}

      - name: Tag Images and Push
        run: |
          for SERVICE in visualization middleware database; do
            docker tag review-galaxy-$SERVICE $REGISTRY/$SERVICE:${{ github.sha }}
            docker tag review-galaxy-$SERVICE $REGISTRY/$SERVICE:latest
            docker push $REGISTRY/$SERVICE:${{ github.sha }}
            docker push $REGISTRY/$SERVICE:latest
          done
